"""
Django settings for CryptoQWeb project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-3#s#+$03-6n5m8t=de4w%2epqtrc=)+7+zq06qw4w#w*_8n4zy')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG defaults to False for production safety
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Get allowed hosts from environment or use defaults
allowed_hosts_str = os.environ.get('ALLOWED_HOSTS', '')
if allowed_hosts_str:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = [
        'cryptoq.onrender.com',
        'localhost',
        '127.0.0.1',
        os.environ.get('RENDER_EXTERNAL_HOSTNAME', ''),
    ]
# Filter out empty strings and add render hostname if available
ALLOWED_HOSTS = [host for host in ALLOWED_HOSTS if host]
# Add Render's default hostname pattern
if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(os.environ.get('RENDER_EXTERNAL_HOSTNAME'))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sentiment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Must be after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CryptoQWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CryptoQWeb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Render-ready: auto-switch to PostgreSQL when DATABASE_URL is set; fallback to SQLite
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600,
        ssl_require=False,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets'),
]

# Ensure static files finders are configured
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# WhiteNoise static files storage for production
# Use StaticFilesStorage (not compressed) to avoid image hashing issues
try:
    import whitenoise
    # Always use StaticFilesStorage (not compressed) for reliable image serving
    # This ensures images are served without hash names, making URLs predictable
    STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'
except ImportError:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# WhiteNoise configuration - Critical for production image serving
if 'whitenoise.middleware.WhiteNoiseMiddleware' in MIDDLEWARE:
    try:
        import whitenoise
        # Set root to staticfiles directory (absolute path for reliability)
        staticfiles_path = os.path.join(BASE_DIR, 'staticfiles')
        # Don't fail if manifest is missing - serve files directly
        WHITENOISE_MANIFEST_STRICT = False
        # In production (after collectstatic), serve from STATIC_ROOT
        # In development, use finders to dynamically find files
        WHITENOISE_USE_FINDERS = True  # Always use finders to find files from STATICFILES_DIRS
        # Only auto-refresh in development
        WHITENOISE_AUTOREFRESH = DEBUG
        # Add max-age for static files caching (1 year for production, no cache for dev)
        WHITENOISE_MAX_AGE = 31536000 if not DEBUG else 0
        # Root directory for static files (STATIC_ROOT after collectstatic)
        WHITENOISE_ROOT = staticfiles_path
        # Enable automatic index files (if any)
        WHITENOISE_INDEX_FILE = False
    except ImportError:
        pass

# Security settings for production
# Note: Some security settings can interfere with static file serving
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000
    # Don't redirect static files - let WhiteNoise handle them
    SECURE_SSL_REDIRECT = False  # Disabled to allow WhiteNoise to serve static files properly
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
