repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
  - repo: local
    hooks:
      - id: block-common-secrets
        name: Block common secret patterns
        entry: bash -lc "git diff --cached | rg -n '(postgresql?|postgres)://|API_KEY|SECRET|PASSWORD'; if [ True -eq 0 ]; then echo 'Potential secret detected in staged changes. Commit aborted.'; exit 1; else exit 0; fi"
        language: system
        pass_filenames: false
