# Generated by Django 4.2.7 on 2025-10-23 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The input text to analyze')),
                ('level1_prediction', models.CharField(blank=True, choices=[('NOISE', 'Noise'), ('OBJECTIVE', 'Objective'), ('SUBJECTIVE', 'Subjective')], max_length=20, null=True)),
                ('level2_prediction', models.CharField(blank=True, choices=[('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive')], max_length=20, null=True)),
                ('level3_prediction', models.CharField(blank=True, choices=[('NEUTRAL_SENTIMENT', 'Neutral Sentiment'), ('QUESTION', 'Question'), ('ADVERTISEMENT', 'Advertisement'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=20, null=True)),
                ('final_classification', models.CharField(help_text='Human-readable final classification', max_length=100)),
                ('confidence_scores', models.JSONField(default=dict, help_text='Confidence scores for each level')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Sentiment Analysis',
                'verbose_name_plural': 'Sentiment Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
