# Generated by Django 5.2.7 on 2025-11-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentanalysis',
            name='platform',
            field=models.CharField(choices=[('REDDIT', 'Reddit'), ('TWITTER', 'Twitter'), ('YOUTUBE', 'YouTube')], default='REDDIT', help_text='Platform source of the text', max_length=20),
        ),
    ]
